name=FluxGarage RoboEyes
version=1.2.0
author=Dennis Hoelscher <dennis@fluxgarage.com>
maintainer=Dennis Hoelscher <dennis@fluxgarage.com>
sentence=Draws smoothly animated robot eyes on OLED displays, using the Adafruit GFX library.
paragraph=Robot eye shapes are configurable in terms of width, height, border radius and space between. 17 different mood expressions (default, tired, angry, happy, alert, bored, despair, disoriented, excited, focused, furious, sad, scared, sleepy, surprised, worried, annoyed), gaze directions, and animations (autoblinker, idle, laughing, confused) are available. All transitions are fluid and smoothly tweened.
category=Display
url=https://github.com/FluxGarage/RoboEyes
architectures=*
depends=Adafruit GFX Library
